#!/bin/bash
# ########################################################################
#  Author: Honda Bhyat  
#  Company: Prolifics
#  Purpose: Single command to stop the docker-compose 
# ########################################################################
# This prevents running the script if any of the variables have not been set
set -o nounset
# This automatically exits the script if any error occurs while running it
set -o errexit
echo "**********************************************************************"
echo "* Lets bring things down.                                            *"
echo "**********************************************************************"
#source .profile
cd /app/ITX_Launcher/$1
export ITX_ENV=$1 
docker-compose down
cd /app/ITX_Launcher
