SELECT 
GUID,
SOURCE_SYSTEM_ID,
CREATED_DATE_TIME,
BATCH_ID,
PRODUCT_TYPE,
TRANSACTION_TYPE,
DATE_TIME_PROCESSED,
PROCESSED_STATUS,
PRODUCT_ID,
POLICY_NUMBER
FROM dbo.CTP_ITXA_TRANS_HIST where BATCH_ID=? AND PRODUCT_TYPE=? ORDER BY BATCH_ID;